### ISSUE TITLE
Empty repo?

### ISSUE THREAD

**Issue by trolund** [iyyel/game-of-life-scala#1]
Ah, the majestic barren lands of 'game-of-life'! 🌱 Behold, the empty canvas where life is yet to bloom, the silence before the storm of code commits! Let's sprinkle some digital magic and watch this repository burst into a vibrant ecosystem of algorithms and simulations. Who's ready to breathe life into this digital realm? 🚀✨

**Comment by itsdanieldk** [comment]
Not anymore!

@trolund
